// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR8iexT2g4e7V353kORqTAHwsBwf0y9lM',
    appId: '1:569763882661:web:bb1fbf0681b85e5f634f4c',
    messagingSenderId: '569763882661',
    projectId: 'jeuxbaord',
    authDomain: 'jeuxbaord.firebaseapp.com',
    storageBucket: 'jeuxbaord.firebasestorage.app',
    measurementId: 'G-0K162NWLVQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk0qtLHfOttcHA5oHEz4qdkx3mt5mjQ3o',
    appId: '1:569763882661:android:344cd1cb30158eeb634f4c',
    messagingSenderId: '569763882661',
    projectId: 'jeuxbaord',
    storageBucket: 'jeuxbaord.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN53etzuH-0JpZYnSyBUpkNplG1C0zOkw',
    appId: '1:569763882661:ios:331ebd5c8354985a634f4c',
    messagingSenderId: '569763882661',
    projectId: 'jeuxbaord',
    storageBucket: 'jeuxbaord.firebasestorage.app',
    iosBundleId: 'com.jeuxbaord.app.untitled',
  );
}
